### ISSUE TITLE
The regexps ciBadgeRegexp/charmBadgeRegexp don't like URI query component 

### ISSUE THREAD

**Issue by taurus-forever** [jnsgruk/releasegen#3]
Hi,

The regexp [ciBadgeRegexp/charmBadgeRegexp](https://github.com/jnsgruk/releasegen/commit/e3599c2e4af1dc42940aad2320270fc8faa7939d#diff-9e22954882e7ba3a509f8b35bb34d51849c03ec3ede027647c64eeb8ec2e5d88R8-R12) don't like URI query component like `?branch=main&event=schedule`.

IMHO, we should improve it to support complex badges on [release.juju.is](https://releases.juju.is/).
Example: [new badges](https://github.com/canonical/mysql-k8s-bundle/pull/32/files) committed to the repository `mysql-k8s-bundle` but  Status column is not shown (like on [Observability](https://releases.juju.is/?team=Observability)).

It is due to [regexp](https://github.com/jnsgruk/releasegen/commit/e3599c2e4af1dc42940aad2320270fc8faa7939d#diff-9e22954882e7ba3a509f8b35bb34d51849c03ec3ede027647c64eeb8ec2e5d88R8-R12) which doesn't like URL query components `?branch=main` and `?event=schedule`.

Are query components forbidden there on purpose?
I think we need to expand a regexp there to bypass URL query components.
Tnx!

**Comment by jnsgruk** [comment]
Hi

So @lucabello was the original author of this piece - but one observation I'd make is that `releasegen` is only looking at the default branch in any case - so specifying one is not necessarily useful/

**Comment by lucabello** [comment]
The current behavior is indeed to take the default branch and the latest ci execution.

For different branches, the main use case I see is when you maintain multiple "default" branches and run CI on both; the problem with this is that even if we allowed it, you would not be able to distinguish between the badge on the releases.juju.is page; the badges will look the same, and only differ by their link, which isn't great for an overview page imho.

For different events, I'm not sure what the use case is: filter out the ci results when it's not run on schedule? Since for charms the relevant stages are mostly gonna be *release*, *test*, or *release libraries*, I don't see much value in adding this; again, this is not reflected in the badge itself, so I think it could be somewhat misleading.

I have no problems with this change in general, though I feel it's not really necessary and it creates the risk of having too many badges, cluttering the view.

If I can give my two cents on your use case, my personal suggestion would be to only choose badges that are representative of the repository status: looking at the [mysql-k8s-bundle](https://github.com/canonical/mysql-k8s-bundle), what I would go for is just **tests** (is this charm working? are all of my charms working?) and **releases** (is this charm being released? are all of my charms being released?); I would remove the **bundle update** badge as that doesn't answer a question on the charm status, but rather on the ci status itself.

**Comment by lucabello** [comment]
Reporting here some updates from external conversations.

The main use case for different events is to be able to run a specific CI (i.e., tests) both on PRs (on every commit) and on schedule (for `main` only). Having a `?event=schedule` selector would allow to only show the latter, which is the relevant one for the repository status.

What I don't like about this addition is that, as I mentioned, none of this information is reflected in the badge itself; if that selector is applied only to some badges, you would have no way of knowing except for clicking each one of them.  
Furthermore, *quality checks on PRs* and *scheduled tests on main* are semantically different things. They "can" perform the same action, but they are not the same thing.

I think a better solution to this problem would to split the *PRs CI* and the *on-schedule CI* in two different workflows, and then only add the badge for the latter. I'd encourage extracting the common part in a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) and separating the two. This approach allows performing only the relevant actions in each workflow (e.g., do you need linting on `main`? what if you tied the scheduled CI with an [update-libs](https://github.com/canonical/observability/blob/main/.github/workflows/update-libs.yaml) worfklow?)
